module.exports = {
    // 200+ features data structure
    categories: {
        main: {
            '📱 Menu Utama': 'mainMenu',
            '🛒 Toko Online': 'onlineShop',
            '💳 Pembayaran': 'paymentMenu',
            '📊 Laporan': 'reportsMenu',
            '⚙️ Pengaturan': 'settingsMenu',
            '👥 Customer Service': 'csMenu'
        },
        shop: {
            '📦 Produk': 'productList',
            '🛍️ Keranjang': 'shoppingCart',
            '📋 Pesanan': 'myOrders',
            '🔍 Cari': 'searchProduct',
            '⭐ Review': 'productReviews',
            '🏪 Profil': 'storeProfile'
        },
        tools: {
            '📅 Jadwal': 'schedule',
            '📢 Broadcast': 'broadcast',
            '📱 Blast': 'waBlast',
            '📊 Analitik': 'analytics',
            '📈 Marketing': 'marketingTools',
            '🤖 Auto Reply': 'autoReply',
            '🎨 Stiker': 'stickerMaker',
            '📥 Download': 'downloader',
            '🖼️ Editor': 'imageEditor',
            '🎵 Musik': 'musicFeature',
            '🎮 Games': 'games',
            '📰 News': 'news',
            '🌤️ Cuaca': 'weather',
            '📱 TikTok': 'tiktokDl',
            '📸 Instagram': 'igDl',
            '🎥 YouTube': 'ytDl',
            '🎭 AI Chat': 'aiChat',
            '🎨 AI Image': 'aiImage',
            '🔍 Search': 'searchFeature',
            '📄 Translate': 'translate',
            '📊 Calculator': 'calculator',
            '💱 Currency': 'currency',
            '📅 Calendar': 'calendar',
            '⏰ Alarm': 'alarm',
            '📝 Notes': 'notes',
            '🔐 Password': 'passwordGen',
            '📊 QR Code': 'qrCode',
            '📷 OCR': 'ocrFeature',
            '📧 Email': 'emailSender',
            '📞 Phone': 'phoneLookup',
            '📍 Location': 'location',
            '📊 Poll': 'createPoll',
            '📢 Announcement': 'announcement',
            '🎁 Giveaway': 'giveaway',
            '📊 Survey': 'survey',
            '📈 Chart': 'createChart',
            '📊 Report': 'generateReport',
            '💳 VCard': 'vcard',
            '📱 Contact': 'contact',
            '🔖 Bookmark': 'bookmark',
            '📊 Statistic': 'statistic',
            '📈 Growth': 'growth',
            '💰 Finance': 'finance',
            '📊 KPI': 'kpi',
            '🎯 Target': 'target',
            '📈 Performance': 'performance',
            '💵 Revenue': 'revenue'
        }
    }
};
